Repository containous/traefik-extra-service-fabric, pull requests merged in 2018-04, with the labels that each got.

#26 Priority and weight as Int.
  servicefabric_config.go
  servicefabric_labelfuncs.go
Labels: kind/enhancement

#27 fix: backend name for stateful service.
  servicefabric_tmpl.go
Labels: kind/bug/fix, status/2-needs-review

#28 fix: backend name for stateful service.
  Gopkg.lock
  servicefabric.go
  servicefabric_config.go
  servicefabric_config_test.go
  servicefabric_test.go
  servicefabric_tmpl.go
Labels: kind/bug/fix, status/2-needs-review

#30 Use shared labels methods.
  Gopkg.lock
  Gopkg.toml
  servicefabric_config.go
Labels: kind/enhancement, status/2-needs-review

#29 Healthcheck headers
  Gopkg.lock
  Gopkg.toml
  servicefabric_config_test.go
  servicefabric_tmpl.go
Labels: kind/enhancement, status/2-needs-review

#33 Adding Application Insights integration
  Gopkg.lock
  servicefabric.go
Labels: kind/enhancement, status/3-needs-merge
